[server]
headless = true

# âœ… Add these lines for Streamlit Cloud to install OCR packages
[packages]
apt_packages = ["tesseract-ocr", "poppler-utils"]

[theme]
primaryColor="#919dee"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F8F9FA"
textColor="#000000"
